#include "images.h"

const ext_img_desc_t images[30] = {
    { "bg", &img_bg },
    { "run", &img_run },
    { "update", &img_update },
    { "weather_small", &img_weather_small },
    { "squats", &img_squats },
    { "pushups", &img_pushups },
    { "lunges", &img_lunges },
    { "burbees", &img_burbees },
    { "mountain_climb", &img_mountain_climb },
    { "jump_rope", &img_jump_rope },
    { "glute_bridges", &img_glute_bridges },
    { "superman", &img_superman },
    { "plankholds", &img_plankholds },
    { "alternating_bird_dogs", &img_alternating_bird_dogs },
    { "cloud", &img_cloud },
    { "rain", &img_rain },
    { "sun", &img_sun },
    { "temperature", &img_temperature },
    { "arrow_l", &img_arrow_l },
    { "arrow_r", &img_arrow_r },
    { "u1", &img_u1 },
    { "u2", &img_u2 },
    { "u3", &img_u3 },
    { "u4", &img_u4 },
    { "u5", &img_u5 },
    { "u6", &img_u6 },
    { "u7", &img_u7 },
    { "u8", &img_u8 },
    { "u9", &img_u9 },
    { "u10", &img_u10 },
};
